### ISSUE TITLE
Questions about formatting pitts30k

### ISSUE THREAD

**Issue by shuimushan** [gmberton/datasets_vg#12]
After running the code, I get correct separation but also the request failed notifications as below. Why are there so many notifications?

I found 51840 images in /media/sda5/datasets/pitts30k/images

request failed [None]: https://a.tile.openstreetmap.org/17/36404/49406.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49407.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49408.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49409.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49410.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49411.png
request failed [None]: https://a.tile.openstreetmap.org/17/36404/49412.png

**Comment by gmberton** [comment]
Hi, that seems correct. You can ignore the "request failed" messages, those just mean that the maps were not created. The maps are just a nice-to-have for visualization and do not affect the dataset.
Those failed requests are due to a [staticmap](https://github.com/komoot/staticmap) issue: the code uses the staticmap library to download a map of the area, but that doesn't work anymore, so until I fix it the maps won't be created automatically.
If the map was correctly created, it would look like this
![map_pitts30k](https://github.com/gmberton/VPR-datasets-downloader/assets/49533159/b65ebc0c-ffa4-4431-9a0c-686594caedb8)
