### ISSUE TITLE
msls datasets

### ISSUE THREAD

**Issue by lv162** [gmberton/datasets_vg#21]
Hello
I want to know how to use your code to process the msls dataset. After processing with your code, aren't the msls-test dataset and the msls-val dataset the same? Also, what is the msls-challenge dataset mentioned in the literature?
I am looking forward to your answer，thank you.

**Comment by HUSTNO1WXY** [comment]
I also want to know, do you have solve this problem?

**Comment by gmberton** [comment]
1) Yes. You can find thorough explanation on our splits in our CVPR 2022 Oral paper [Deep Visual Geo-localization Benchmark](https://arxiv.org/abs/2204.03444)
2) The MSLS-challenge is another split with withheld labels that needs to be evaluated on the authors' servers. We don't format it because there are no labels for those images, see previous issues for more details
